export interface KEYType {
  pitch: string
  blackKey: boolean
  key: string
}

export const KEYS: KEYType[] = [
  { pitch: 'C4', blackKey: false, key: 't' },
  { pitch: 'C#4', blackKey: true, key: 'T' },
  { pitch: 'D4', blackKey: false, key: 'y' },
  { pitch: 'D#4', blackKey: true, key: 'Y' },
  { pitch: 'E4', blackKey: false, key: 'u' },
  { pitch: 'F4', blackKey: false, key: 'i' },
  { pitch: 'F#4', blackKey: true, key: 'I' },
  { pitch: 'G4', blackKey: false, key: 'o' },
  { pitch: 'G#4', blackKey: true, key: 'O' },
  { pitch: 'A4', blackKey: false, key: 'p' },
  { pitch: 'A#4', blackKey: true, key: 'P' },
  { pitch: 'B4', blackKey: false, key: 'a' },
  { pitch: 'C5', blackKey: false, key: 's' },
  { pitch: 'C#5', blackKey: true, key: 'S' },
  { pitch: 'D5', blackKey: false, key: 'd' },
  { pitch: 'D#5', blackKey: true, key: 'D' },
  { pitch: 'E5', blackKey: false, key: 'f' },
  { pitch: 'F5', blackKey: false, key: 'g' },
  { pitch: 'F#5', blackKey: true, key: 'G' },
  { pitch: 'G5', blackKey: false, key: 'h' },
  { pitch: 'G#5', blackKey: true, key: 'H' },
  { pitch: 'A5', blackKey: false, key: 'j' },
  { pitch: 'A#5', blackKey: true, key: 'J' },
  { pitch: 'B5', blackKey: false, key: 'k' },
  { pitch: 'C6', blackKey: false, key: 'l' },
  { pitch: 'C#6', blackKey: true, key: 'L' },
  { pitch: 'D6', blackKey: false, key: 'z' },
  { pitch: 'D#6', blackKey: true, key: 'Z' },
  { pitch: 'E6', blackKey: false, key: 'x' },
  { pitch: 'F6', blackKey: false, key: 'c' },
  { pitch: 'F#6', blackKey: true, key: 'C' },
  { pitch: 'G6', blackKey: false, key: 'v' },
  { pitch: 'G#6', blackKey: true, key: 'V' },
  { pitch: 'A6', blackKey: false, key: 'b' },
  { pitch: 'A#6', blackKey: true, key: 'B' },
  { pitch: 'B6', blackKey: false, key: 'n' },
]

export const KEY_MAP: { [p: string]: { pitch: string; octave: number } } = {
  t: { pitch: 'C', octave: 4 },
  T: { pitch: 'C#', octave: 4 },
  y: { pitch: 'D', octave: 4 },
  Y: { pitch: 'D#', octave: 4 },
  u: { pitch: 'E', octave: 4 },
  i: { pitch: 'F', octave: 4 },
  I: { pitch: 'F#', octave: 4 },
  o: { pitch: 'G', octave: 4 },
  O: { pitch: 'G#', octave: 4 },
  p: { pitch: 'A', octave: 4 },
  P: { pitch: 'A#', octave: 4 },
  a: { pitch: 'B', octave: 4 },
  s: { pitch: 'C', octave: 5 },
  S: { pitch: 'C#', octave: 5 },
  d: { pitch: 'D', octave: 5 },
  D: { pitch: 'D#', octave: 5 },
  f: { pitch: 'E', octave: 5 },
  g: { pitch: 'F', octave: 5 },
  G: { pitch: 'F#', octave: 5 },
  h: { pitch: 'G', octave: 5 },
  H: { pitch: 'G#', octave: 5 },
  j: { pitch: 'A', octave: 5 },
  J: { pitch: 'A#', octave: 5 },
  k: { pitch: 'B', octave: 5 },
  l: { pitch: 'C', octave: 6 },
  L: { pitch: 'C#', octave: 6 },
  z: { pitch: 'D', octave: 6 },
  Z: { pitch: 'D#', octave: 6 },
  x: { pitch: 'E', octave: 6 },
  c: { pitch: 'F', octave: 6 },
  C: { pitch: 'F#', octave: 6 },
  v: { pitch: 'G', octave: 6 },
  V: { pitch: 'G#', octave: 6 },
  b: { pitch: 'A', octave: 6 },
  B: { pitch: 'A#', octave: 6 },
  n: { pitch: 'B', octave: 6 },
}
