export interface KEYType {
  pitch: string
  blackKey: boolean
  key: string
}

export const KEYS: KEYType[] = [
  { pitch: 'F3', blackKey: false, key: 'u' },
  { pitch: 'F#3', blackKey: true, key: 'U' },
  { pitch: 'G3', blackKey: false, key: 'i' },
  { pitch: 'G#3', blackKey: true, key: 'I' },
  { pitch: 'A3', blackKey: false, key: 'o' },
  { pitch: 'A#3', blackKey: true, key: 'O' },
  { pitch: 'B3', blackKey: false, key: 'p' },
  { pitch: 'C4', blackKey: false, key: 'a' },
  { pitch: 'C#4', blackKey: true, key: 'A' },
  { pitch: 'D4', blackKey: false, key: 's' },
  { pitch: 'D#4', blackKey: true, key: 'S' },
  { pitch: 'E4', blackKey: false, key: 'd' },
  { pitch: 'F4', blackKey: false, key: 'f' },
  { pitch: 'F#4', blackKey: true, key: 'F' },
  { pitch: 'G4', blackKey: false, key: 'g' },
  { pitch: 'G#4', blackKey: true, key: 'G' },
  { pitch: 'A4', blackKey: false, key: 'h' },
  { pitch: 'A#4', blackKey: true, key: 'H' },
  { pitch: 'B4', blackKey: false, key: 'j' },
  { pitch: 'C5', blackKey: false, key: 'k' },
  { pitch: 'C#5', blackKey: true, key: 'K' },
  { pitch: 'D5', blackKey: false, key: 'l' },
  { pitch: 'D#5', blackKey: true, key: 'L' },
  { pitch: 'E5', blackKey: false, key: 'z' },
  { pitch: 'F5', blackKey: false, key: 'x' },
  { pitch: 'F#5', blackKey: true, key: 'X' },
  { pitch: 'G5', blackKey: false, key: 'c' },
  { pitch: 'G#5', blackKey: true, key: 'C' },
  { pitch: 'A5', blackKey: false, key: 'v' },
  { pitch: 'A#5', blackKey: true, key: 'V' },
  { pitch: 'B5', blackKey: false, key: 'b' },
  { pitch: 'C6', blackKey: false, key: 'n' },
]

export const KEY_MAP: { [p: string]: { pitch: string; octave: number } } = {
  u: { pitch: 'F', octave: 3 },
  U: { pitch: 'F#', octave: 3 },
  i: { pitch: 'G', octave: 3 },
  I: { pitch: 'G#', octave: 3 },
  o: { pitch: 'A', octave: 3 },
  O: { pitch: 'A', octave: 3 },
  p: { pitch: 'B#', octave: 3 },
  a: { pitch: 'C', octave: 4 },
  A: { pitch: 'C#', octave: 4 },
  s: { pitch: 'D', octave: 4 },
  S: { pitch: 'D#', octave: 4 },
  d: { pitch: 'E', octave: 4 },
  f: { pitch: 'F', octave: 4 },
  F: { pitch: 'F#', octave: 4 },
  g: { pitch: 'G', octave: 4 },
  G: { pitch: 'G#', octave: 4 },
  h: { pitch: 'A', octave: 4 },
  H: { pitch: 'A', octave: 4 },
  j: { pitch: 'B#', octave: 4 },
  k: { pitch: 'C', octave: 5 },
  K: { pitch: 'C#', octave: 5 },
  l: { pitch: 'D', octave: 5 },
  L: { pitch: 'D#', octave: 5 },
  z: { pitch: 'E', octave: 5 },
  x: { pitch: 'F', octave: 5 },
  X: { pitch: 'F#', octave: 5 },
  c: { pitch: 'G', octave: 5 },
  C: { pitch: 'G#', octave: 5 },
  v: { pitch: 'A', octave: 5 },
  V: { pitch: 'A', octave: 5 },
  b: { pitch: 'B#', octave: 5 },
  n: { pitch: 'C', octave: 5 },
}

export const INTERVAL_MAP: string[] = [
  '纯一',
  '小二',
  '大二',
  '小三',
  '大三',
  '纯四',
  '增四',
  '纯五',
  '小六',
  '大六',
  '小七',
  '大七',
  '纯八',
]
